### ISSUE TITLE
Error: package io.branch.referral does not exist on RN=0.56

### ISSUE THREAD

**Issue by xmarianox** [BranchMetrics/react-native-branch-deep-linking-attribution#366] opened 2018-08-07 16:13 UTC
When I try to compile the project it works but I can run the project on simulator.

This is the error on Android Studio console `error: package io.branch.referral does not exist`

My `app/build.gradle` file :

```groovy
apply plugin: "com.android.application"
apply plugin: 'io.fabric'

repositories {
    maven { url 'https://maven.fabric.io/public' }
}

import com.android.build.OutputFile

/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation
 *   entryFile: "index.android.js",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         'bundleIn${productFlavor}${buildType}'
 *   //         'bundleIn${buildType}'
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/**", "ios/**"],
 *
 *   // override which node gets called and with what additional arguments
 *   nodeExecutableAndArgs: ["node"]
 *
 *   // supply additional arguments to the packager
 *   extraPackagerArgs: []
 * ]
 */

apply from: "../../node_modules/react-native/react.gradle"

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion 28
    buildToolsVersion '28.0.2'

    defaultConfig {
        applicationId "com.soylomasandroid"
        minSdkVersion 16
        targetSdkVersion 26
        versionCode 17
        versionName "1.0.15"
        multiDexEnabled true
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }

    signingConfigs {
        release {
            if (project.hasProperty('MYAPP_RELEASE_STORE_FILE')) {
                storeFile file(MYAPP_RELEASE_STORE_FILE)
                storePassword MYAPP_RELEASE_STORE_PASSWORD
                keyAlias MYAPP_RELEASE_KEY_ALIAS
                keyPassword MYAPP_RELEASE_KEY_PASSWORD
            }
        }
    }

    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            // debuggable false
            // shrinkResources enableProguardInReleaseBuilds
            // zipAlignEnabled enableProguardInReleaseBuilds
            // minifyEnabled enableProguardInReleaseBuilds
            // useProguard enableProguardInReleaseBuilds
            //setProguardFiles([getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"])
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

dependencies {
    // From node_modules
    implementation(project(':react-native-firebase')) {
        transitive = false
    }
    implementation project(':react-native-navigation')
    implementation project(':react-native-image-picker')
    implementation project(':react-native-fetch-blob')
    implementation project(':react-native-snackbar')
    implementation project(':react-native-add-calendar-event')
    implementation project(':react-native-facebook-login')
    implementation project(':react-native-linear-gradient')
    implementation project(':react-native-branch')
    implementation(project(':react-native-maps')){
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-maps'
    }
    implementation fileTree(dir: "libs", include: ["*.jar"])

    implementation 'com.android.support:appcompat-v7:28.0.0-rc01'
    implementation 'com.facebook.react:react-native:+'
    // firebase
    implementation 'com.google.firebase:firebase-core:16.0.1'
    implementation 'com.google.firebase:firebase-auth:16.0.2'
    implementation 'com.google.firebase:firebase-database:16.0.1'
    implementation 'com.google.firebase:firebase-storage:16.0.1'
    implementation 'com.google.firebase:firebase-firestore:17.0.4'
    implementation 'com.google.firebase:firebase-analytics:16.0.1'
    implementation 'com.google.firebase:firebase-messaging:17.1.0'
    implementation "com.google.firebase:firebase-ads:15.0.1"
    implementation('com.crashlytics.sdk.android:crashlytics:2.7.1@aar') {
        transitive = true
    }
    implementation 'com.facebook.android:facebook-android-sdk:4.35.0'
    implementation 'com.google.android.gms:play-services-base:15.0.1'
    implementation 'com.google.android.gms:play-services-maps:15.0.1'
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

apply plugin: 'com.google.gms.google-services'
```

and this is the project `build.gradle`

```groovy
// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        google()
        jcenter()
        maven { url 'https://maven.fabric.io/public' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.4'
        classpath 'com.google.gms:google-services:4.0.1'
        classpath 'io.fabric.tools:gradle:1.25.4'
    }
}
allprojects {
    repositories {
        google()
        mavenLocal()
        jcenter()
        maven {
            url 'https://maven.google.com'
            // Alternative URL is 'https://dl.google.com/dl/android/maven2/'
        }
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}
subprojects {
    project.configurations.all {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'com.android.support'
                    && !details.requested.name.contains('multidex')) {
                details.useVersion "28.0.0-rc01"
            }
        }
    }
}
subprojects {
    project.configurations.all {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'com.google.firebase') {
                details.useVersion "+"
            }
        }
    }
}

subprojects {
    project.configurations.all {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'com.google.android.gms') {
                details.useVersion "+"
            }
        }
    }
}
```

My stack:
```
react: 16.4.1
react-native: 0.56.0
react-native-branch: 2.3.3

Node: 9.11.1
Yarn: 1.9.4
```

**Comment by guymoreillon** [comment] 2018-09-06 13:01
Same setup here, same punishment. Did you find a solution?

**Comment by isrdoc** [comment] 2018-09-20 08:27
I've also had this problem. The way I got it working is by going into react-native-branch build.gradle file and explicitly setting dependencies like this:
```
dependencies {
    implementation 'com.facebook.react:react-native:0.56.0' // From node_modules
    api files('libs/Branch-2.19.0.jar') // From node_modules <-- this one is important
}
```
Like [jdee said](https://github.com/BranchMetrics/react-native-branch-deep-linking/issues/256#issuecomment-328678061):

> I have a feeling this happens when Android dependencies are taken from node_modules. Maybe this shows up for Branch because the SDK includes a jar. This might be necessary with any jar from node_modules. But that's speculation on my part.

Also I've done closing Android Studio, did a cd android/ && ./gradlew clean and reopened the project.

This problem will probably come back when node_modules are reinstalled, so I'm keeping an eye on that react-native-branch build.gradle file.

Java compiler still reports:
```
/node_modules/react-native-branch/android/src/main/java/io/branch/rnbranch/RNBranchModule.java:
uses or overrides a deprecated API.
Recompile with -Xlint:deprecation for details.
```
But that is a warning and doesn't fail the build.

**Comment by guymoreillon** [comment] 2018-09-20 08:36
Interesting. Personally I ditched the whole react-native-branch-deep-linking thing, integrated Branch at the native level and notified the react native app through an RCTDeviceEventEmitter.

**Comment by limouren** [comment] 2018-10-09 20:54
Hi all. It could be worked around by depending on the jar that comes directly from `react-native-branch`. Just add the following dependency to `app/build.gradle`:

```
dependencies {
    // ...
    compile fileTree(dir: "../../node_modules/react-native-branch/android/libs", include: ["*.jar"])
    // ..
}
```

**Comment by bhavukjain1** [comment] 2019-02-09 20:04
@csalmi-branch Yes, it's not working.

**Comment by csalmi-branch** [comment] 2019-02-13 03:35
@bhavukjain1 Did you try any of the work-arounds that others have listed above? Can you also provide us with more details about your configuration? What version are you using, etc.

**Comment by p-dealwis** [comment] 2019-02-20 21:01
@csalmi-branch been stuck on this issue as well. Cannot import the `io.branch.referral.Branch` class for use in the `MainApplication.java` file. Have tried doing a gradle clean and build to no avail. The problem seems to arise from a namespace collision from what I understand.
```
// import Branch and RNBranch
import io.branch.rnbranch.RNBranchPackage;
import io.branch.referral.Branch; // <---- io.branch is confused with the one above
```
My Android knowledge isn't the best so there's maybe something I am missing here?

**Comment by csalmi-branch** [comment] 2019-02-21 21:17
Thanks for the updated information! We will take a look into this issue.

**Comment by bhavukjain1** [comment] 2019-02-22 10:09
I got this fixed by updating the gradle file.

https://github.com/BranchMetrics/react-native-branch-deep-linking#updating-from-an-earlier-version.

Open the `android/app/build.gradle` file in your project.

Remove this line:

```gradle
implementation fileTree(dir: 'libs', include: ['*.jar'])
```

Add this line:

```gradle
implementation "io.branch.sdk.android:library:3.0.4"
```

The result should be something like
```gradle
dependencies {
    implementation project(':react-native-branch')
    implementation "io.branch.sdk.android:library:3.0.4"
    implementation "com.android.support:appcompat-v7:23.0.1"
    implementation "com.facebook.react:react-native:+"  // From node_modules
}
```

**Comment by csalmi-branch** [comment] 2019-02-23 00:18
@bhavukjain1 I'm glad that helped fix this issue! I would have only expected that particular fix to be needed if you are using V3.0.0, but if you are using an earlier version and it helped as well, I'm glad to hear it.

@p-dealwis What version of of Branch React Native are you using?

**Comment by p-dealwis** [comment] 2019-02-23 01:18
@csalmi-branch I am on `v3.0.0-beta.1` and can confirm @bhavukjain1's fix worked! I had ignored that step in the documentation since I was not upgrading from a previous version.

**Comment by csalmi-branch** [comment] 2019-02-23 01:32
Thanks for that call out. I'll see if there is a docs update that we can make to prevent future confusion.

Is anyone else facing this issue even with the gradle file update?

**Comment by flexbox** [comment] 2019-03-01 12:18
@csalmi-branch Confirmed here

With `2.3.4`
<img width="835" alt="image" src="https://user-images.githubusercontent.com/360936/53637779-fa24a580-3c1b-11e9-9482-2f6ed3f8fad1.png">

I needed to downgrade to `2.3.3` for a successful buid

**Comment by csalmi-branch** [comment] 2019-03-01 18:49
@flexbox are you able to use the newest beta version (v3..0.0-beta.2)? The main change in the beta version is how we pull the native SDK build, which helps to fix these compilation errors.

**Comment by flexbox** [comment] 2019-03-04 06:38
Seams the error is the same if I upgrade to `"react-native-branch": "3.0.0-beta.2",`

<img width="1045" alt="circle" src="https://user-images.githubusercontent.com/360936/53714898-64259080-3e50-11e9-806f-853f12ff58aa.png">

**Comment by jdee** [comment] 2019-03-07 00:04
@flexbox Did you follow these instructions for updating to 3.0.0-beta? https://github.com/BranchMetrics/react-native-branch-deep-linking#updating-from-an-earlier-version-or-starting-with-v300

**Comment by flexbox** [comment] 2019-03-22 10:55
Hello @jdee 
I double checked the [instructions for migrating to v3.0.0](https://github.com/BranchMetrics/react-native-branch-deep-linking#updating-from-an-earlier-version-or-starting-with-v300)
1. bumped to `"react-native-branch": "3.0.0-beta.3",`
2. Rebuild again

CircleCI is still complaining for another issue now: 
```
MainApplication.java:76: error: cannot find symbol
    RNBranchModule.getAutoInstance(this);
    ^
  symbol:   variable RNBranchModule
  location: class MainApplication
1 error
 FAILED
```

<img width="906" alt="Untitled" src="https://user-images.githubusercontent.com/360936/54818294-2ec6d280-4c99-11e9-8fcb-5990892637a9.png">

**Comment by jdee** [comment] 2019-03-29 00:42
@flexbox Did you also `import io.branch.rnbranch.RNBranchModule`? (See, e.g. https://github.com/BranchMetrics/react-native-branch-deep-linking/blob/master/examples/webview_example/android/app/src/main/java/com/webview_example/MainApplication.java#L9). I think in some cases AndroidStudio will do this for you, but you may have to insert it manually. I guess we may need to add that to the docs.

**Comment by marudy** [comment] 2019-03-29 12:04
I concur that this problem exists for me as well.

Branch version: 2.3.5
React Native version: 0.58.6

My `MainApplication.java` looks like that:
```
...
import io.branch.referral.Branch;
import io.branch.rnbranch.RNBranchPackage;
...
@Override
    public void onCreate() {
        super.onCreate();
        SoLoader.init(this, /* native exopackage */ false);
        Branch.getAutoInstance(this);
    }
```

And I get the following compilation error:
```
> Task :app:compileDebugJavaWithJavac FAILED
/.../android/app/src/main/java/com/.../MainApplication.java:29: error: cannot find symbol
import io.branch.referral.Branch;
                         ^
  symbol:   class Branch
  location: package io.branch.referral
/.../android/app/src/main/java/com/.../MainApplication.java:98: error: cannot find symbol
        Branch.getAutoInstance(this);
        ^
  symbol:   variable Branch
  location: class MainApplication
2 errors
```

**Comment by Asleepace** [comment] 2019-04-05 21:58
Ya I'm seeing this problem on `react-native: 0.57.9` and `react-native-branch: 2.3.5`

**Comment by niparx** [comment] 2019-04-16 14:41
Why do you release it, if it is not compiling without dancing with drums?

**Comment by almirfilho** [comment] 2019-04-25 02:37
@marudy Have you managed to fix it? I'm using the exact same versions as you and getting the same error. Any help is appreciated, thanks.

**Comment by marudy** [comment] 2019-04-27 18:06
@almirfilho what I did is downgraded to a previous version that we were using in another project and worked... `"react-native-branch": "2.1.1"`

**Comment by flexbox** [comment] 2019-05-09 12:36
I tried again to bump to `3.0.0` with React Native `0.59.8`
And It's not working. I rolled back to "react-native-branch": "2.3.3"

**Comment by VivekSharma-zymr** [comment] 2019-07-16 06:43
I am facing the same issue cannot implement the method in **MainApplication.java**
` @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
    RNBranchModule.getAutoInstance(this);
  }`

**Comment by gdeluna-branch** [comment] 2023-05-17 10:52
Closing out old issues. Please make a new issue if this repros on the latest.

**Closed by gdeluna-branch** 2023-05-17 10:52 UTC
