### ISSUE TITLE
How to setRequestMetadataKey for segment

### ISSUE THREAD

**Issue by 0xpatrickdev** [BranchMetrics/react-native-branch-deep-linking-attribution#379] opened 2018-09-28 20:02 UTC
Hey folks,

The [documentation](https://docs.branch.io/pages/integrations/segment/#pass-segment-anonymous-id) on the website is a little sparse/unclear for React Native. 

There are two PR's (for iOS and Android) that seem to implement the `setRequestMetadataKey` method: #210 & #321, but they are unfortunately not documented.

Here are the relevant excerpts from the Branch website:

**iOS:** 
_Inside didFinishLaunchingWithOptions_
```
Branch *branch = [Branch getInstance];
[[Branch getInstance] setRequestMetadataKey:@"$segment_anonymous_id" value:[[SEGAnalytics sharedAnalytics] getAnonymousId]];
```

**Android:**
_Before you initialize in your Application#onCreate or Deep Link Activity's #onCreate._
```
Branch.getInstance().setRequestMetadata("$segment_anonymous_id", com.segment.analytics.Analytics.with(this).getAnalyticsContext().traits().anonymousId());
...
Branch.initSession(...);
```
_In the above snippet, this is the Activity context._

I am using [react-native-analytics-segment-io](https://github.com/leoilab/react-native-analytics-segment-io), which seems to be the preferred solution for integrating Segment with React Native.

Here are my attempts at implementing this: 

**iOS**
```
#import "AppDelegate.h"
#import <react-native-branch/RNBranch.h>
+ #import <Analytics/SEGAnalytics.h>
@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
+ [RNBranch setRequestMetadataKey:@"$segment_anonymous_id" value:[[SEGAnalytics sharedAnalytics] getAnonymousId]];
  [RNBranch initSessionWithLaunchOptions:launchOptions isReferrable:YES];
...
}
```
_The actual segment module is `<RNAnalyticsSegmentIO/RNASegmentIO.h>`, so maybe that's where I'm going wrong. The app builds correctly with the code above, but closes right after opening._

**Android**
```
import io.branch.rnbranch.*;
+ import com.leo_pharma.analytics.AnalyticsPackage;

public class MainActivity extends ReactActivity {

    @Override
    protected void onStart() {
        super.onStart();
+       RNBranchModule.getInstance().setRequestMetadata("$segment_anonymous_id", com.leo_pharma.analytics.AnalyticsPackage.with(this).getAnalyticsContext().traits().anonymousId());
        RNBranchModule.initSession(getIntent().getData(), this);
    }
}
```
_I am unable to get the Android app to build with this, the build logs say `error: cannot find symbol` (pointing to `AnalyticsPackage.with(this)`)._

Any help or a point in the right direction would be greatly appreciated. Part of me is thinking that this integration may not even be possible since Segment is set up on the JavaScript side of things, and the `anonymousId` may not be available in time for Branch.

**Comment by sequoiaat** [comment] 2018-09-28 20:53
@pcooney10  We will try to reproduce this and see if we can propose a path forward

**Comment by pcooney10** [comment] 2018-09-28 21:06
@sequoiaat awesome, thank you. I also opened an [issue](https://github.com/leoilab/react-native-analytics-segment-io/issues/71) in `react-native-analytics-segment-io` as well. The maintainers have been responsive in the past and can hopefully provide some insights here as well.

**Comment by pcooney10** [comment] 2018-10-16 19:12
Hey @sequoiaat or anyone else that may be reading along, is there anyway to use the `setRequestMetadataKey` or `setRequestMetadata` method with this lib?

**Comment by sequoiaat** [comment] 2018-10-17 17:02
@pcooney10  will try to replicate steps today and post an update

**Comment by pcooney10** [comment] 2018-10-22 22:43
Ok thank you @sequoiaat, I appreciate you getting back to me

**Comment by mjgaylord** [comment] 2018-11-12 16:04
@pcooney10 @sequoiaat  just wondering if you managed to get this working? We're also trying to use the `setRequestMetadata` call in our app and coming up short with a solution.

**Comment by pcooney10** [comment] 2018-12-05 15:39
Hey @sequoiaat, would you mind sharing where you ran into issues / any additional findings you may have? Thanks !

**Comment by sequoiaat** [comment] 2018-12-06 19:56
@pcooney10 @mjgaylord  Sorry we had tried to replicate it but we ran into some error on linking react native analytic segment io and could not reproduce the scenario. then we got pulled a bit sideways.  We will try to  work on this later part of today and share what we find.

**Comment by sequoiaat** [comment] 2018-12-10 17:00
@pcooney10 @mjgaylord  - No luck yet on it at our end to get it working. we will try to work on a path forward for this.

**Comment by pcooney10** [comment] 2018-12-10 17:48
Ok thank you for the update @sequoiaat

**Comment by sequoiaat** [comment] 2018-12-13 17:46
@pcooney10  -  We looked further into this yesterday and reviewed the segment documentation Not sure if it gives you a path forward but here is what we noticed. 

Please refer the link https://segment.com/docs/sources/mobile/android/#anonymousid
According to this link  with(context).getAnalyticsContext().traits().anonymousId() is applicable to com.segment.analytics.Analytics. 

![image](https://user-images.githubusercontent.com/20103264/49956477-1d13a900-feba-11e8-9663-756a83c052ff.png)

- When we followed the documentation and  added “com.segment.analytics.Analytics” instead of ”com.leo_pharma.analytics.AnalyticsPackage”(the segment library’s analytics package path), the app is building.  

This is a dependency added to the segment sdk while importing the segment library. So our conclusion is that the irrespective of the libraries we use for segment, we can use 
Branch.getInstance().setRequestMetadata("$segment_anonymous_id", com.segment.analytics.Analytics.with(this).getAnalyticsContext().traits().anonymousId())

Can you please check this and see if it solves the problem

**Comment by csalmi-branch** [comment] 2019-01-04 20:04
@pcooney10 Did either of your potential fixes listed in your previous comment work to resolve this issue, or are you still experiencing it?

**Comment by martintreurnicht** [comment] 2019-02-05 02:43
This has nothing to do with segment, currently `setRequestMetadata` function isn't exposed from the native code. It's as simple as just adding `@ReactMethod` annotations and exposing that function from what i can see. I've tried to do this myself and test it but i have no idea how to get it working.

**Comment by pcooney10** [comment] 2019-02-05 17:58
@csalmi-branch unfortunately I haven't had time to test this out. I still have my suspicions about @sequoiaat's solution if segment is initialized on the js side of things, as we wouldn't have the `anonymousId` in time.

It seems like it may be possible with [segmentio/analytics-react-native](https://github.com/segmentio/analytics-react-native), if it's set up on the native side, but I ran into another road block, described in #401, and unfortunately was not provided much color from the Branch dev team.

@martintreurnicht I am not sure it's as simple as exposing a `@ReactMethod` annotation for `setRequestMetadata`, as the `RNBranch` sdk needs to be initialized on the native side of things. And for the `setRequestMetadata` method in particular, it seems like it needs to be called _before_ `initSession()` and `initSessionWithLaunchOptions`. I think if the initialization of this library was moved to the JS side, then it could be just as simple as adding a `@ReactMethod`.

**Comment by csalmi-branch** [comment] 2019-03-29 18:32
Is anyone still experiencing this issue? Sequoia is no longer looking into it, so if there is anyone running into this issue still, we can have someone with a fresh set of eyes investigate.

**Comment by pcooney10** [comment] 2019-04-05 17:45
Hi @csalmi-branch, thank you for following up on this topic again.

It seems that @jdee recently picked up on #401, thank you @jdee !

#426 / the 3.0.0 RC seems like it will address the issue, but I can't say for certain without testing it out again. And to echo the original question, we are looking to implement this behavior with `react-native-branch`: https://docs.branch.io/integrations/segment/#pass-segment-anonymous-id

**Comment by LydGol90** [comment] 2020-05-14 16:27
Hi there, I see this issue is still open from last year but struggling to follow if there is a fix or not. I am current on react-native branch 4.2.1 and I trying to so the Segment integration

Have added:
```
#import <react-native-branch/RNBranch.h>
#import <Analytics/SEGAnalytics.h>


 [RNBranch setRequestMetadataKey:@"$segment_anonymous_id" value:[[SEGAnalytics sharedAnalytics] getAnonymousId]];
 [RNBranch initSessionWithLaunchOptions:launchOptions isReferrable:YES];
```

Do I need to be on a different version or using a more up to date SDK?

Thanks for any help

**Comment by crherman7** [comment] 2021-03-17 14:31
@pcooney10 I have also ran into this issue currently. The reason why iOS was closing immediately for me was because `SEGAnalytics` was not initialized/configured. First you would have to configure it on the native side and then you can make the call to get the `getAnonymousId`. Not sure if your issue is the same as mine, but if you debug in Xcode it lets you know that it was not initialized.

The issue I am trying to solve is making sure that doing a minimal configuration on the native ios/android side with just the write key and then continuing the setup on the react-native side to configure different integrations like amplitude, firebase, etc.

```
analytics.useNativeConfiguration().setup(...)
```

Not sure if this would work, but hoping it will. Let me know if you have any tips or learned lessons over the past year. Thanks!

**Comment by mendes-develop** [comment] 2021-09-14 21:03
Invoking the method `setRequestMetadataKey` from `RNBranch.branch` instead of the `RNBranch` worked for me

```
- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
  [RNBranch.branch setRequestMetadataKey:@"$deep_link_url" value:url.absoluteString]; // this line works now
  if (![RNBranch application:app openURL:url options:options]) {
    return YES;
  }
  return [RNBranch application:app openURL:url options:options];
}
```

This method used to be part of the RNBranch class on previous versions. Maybe something that should be described on the RN docs?

**Closed** 2023-05-17 10:49 UTC
